package com.ingram.dataverse;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Utility implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Utility() {
    }


    public static String getDayByDate(String date) {
		SimpleDateFormat format1 = new SimpleDateFormat("dd-MM-yyyy");
  	    Date dt1;
		try {
			dt1 = format1.parse(date);
			DateFormat format2 = new SimpleDateFormat("EEEE"); 
	  	    return format2.format(dt1);
		} catch (ParseException e) {
			return "INVALID_DATE";
		}
	}

}